apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    {{- include "spring-db-demo.app.labels" . | nindent 4 }}
  name: {{ include "spring-db-demo.fullname" . }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.image.name }}:{{ .Values.image.version }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      ref: {{ .Values.git.ref }}
      uri: {{ .Values.git.uri }}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-8-el7
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
