apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  labels:
    {{- include "spring-db-demo.app.labels" . | nindent 4 }}
  name: {{ include "spring-db-demo.fullname" . }}
spec:
  lookupPolicy:
    local: false
