apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    {{- include "spring-db-demo.app.labels" . | nindent 4 }}
  name: {{ include "spring-db-demo.fullname" . }}
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
  selector:
    {{- include "spring-db-demo.app.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
